// <auto-generated />
using System;
using CrimePortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrimePortal.Migrations
{
    [DbContext(typeof(CRDbContext))]
    [Migration("20251030191540_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrimePortal.Models.CrimeRegister", b =>
                {
                    b.Property<int>("CrimeRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrimeRegisterId"));

                    b.Property<string>("AccusedAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AccusedAge")
                        .HasColumnType("int");

                    b.Property<string>("AccusedGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccusedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccusedRelativeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Act")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarrierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complainant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Court")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CrimeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigatingOfficerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigatingOfficerRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficerRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfIncident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliceStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SampleNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeTo")
                        .HasColumnType("time");

                    b.Property<decimal?>("TotalSeizedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CrimeRegisterId");

                    b.ToTable("CrimeRegisters");
                });

            modelBuilder.Entity("CrimePortal.Models.Pancha", b =>
                {
                    b.Property<int>("PanchaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanchaId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CrimeRegisterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanchaId");

                    b.HasIndex("CrimeRegisterId");

                    b.ToTable("Panchas");
                });

            modelBuilder.Entity("CrimePortal.Models.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SampleId"));

                    b.Property<int>("CrimeRegisterId")
                        .HasColumnType("int");

                    b.Property<string>("SampleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SampleId");

                    b.HasIndex("CrimeRegisterId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("CrimePortal.Models.SeizedItem", b =>
                {
                    b.Property<int>("SeizedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeizedItemId"));

                    b.Property<decimal?>("ApproxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CrimeRegisterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeizedItemId");

                    b.HasIndex("CrimeRegisterId");

                    b.ToTable("SeizedItems");
                });

            modelBuilder.Entity("CrimePortal.Models.Pancha", b =>
                {
                    b.HasOne("CrimePortal.Models.CrimeRegister", "CrimeRegister")
                        .WithMany("Panchas")
                        .HasForeignKey("CrimeRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrimeRegister");
                });

            modelBuilder.Entity("CrimePortal.Models.Sample", b =>
                {
                    b.HasOne("CrimePortal.Models.CrimeRegister", "CrimeRegister")
                        .WithMany("Samples")
                        .HasForeignKey("CrimeRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrimeRegister");
                });

            modelBuilder.Entity("CrimePortal.Models.SeizedItem", b =>
                {
                    b.HasOne("CrimePortal.Models.CrimeRegister", "CrimeRegister")
                        .WithMany("SeizedItems")
                        .HasForeignKey("CrimeRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrimeRegister");
                });

            modelBuilder.Entity("CrimePortal.Models.CrimeRegister", b =>
                {
                    b.Navigation("Panchas");

                    b.Navigation("Samples");

                    b.Navigation("SeizedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
