// <auto-generated />
using System;
using CrimePortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrimePortal.Migrations
{
    [DbContext(typeof(CRDbContext))]
    partial class CRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrimePortal.Models.CrimeRegister", b =>
                {
                    b.Property<int>("CrimeRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CrimeRegisterId"));

                    b.Property<string>("AccusedAddress")
                        .HasColumnType("text");

                    b.Property<int?>("AccusedAge")
                        .HasColumnType("integer");

                    b.Property<string>("AccusedGender")
                        .HasColumnType("text");

                    b.Property<string>("AccusedName")
                        .HasColumnType("text");

                    b.Property<string>("AccusedRelativeName")
                        .HasColumnType("text");

                    b.Property<string>("Act")
                        .HasColumnType("text");

                    b.Property<decimal?>("BeerLiters")
                        .HasColumnType("numeric");

                    b.Property<string>("CarrierName")
                        .HasColumnType("text");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complainant")
                        .HasColumnType("text");

                    b.Property<string>("Court")
                        .HasColumnType("text");

                    b.Property<DateTime>("CrimeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeshiLiquorLiters")
                        .HasColumnType("numeric");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<decimal?>("ForeignLiquorLiters")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("HandBhattiLiters")
                        .HasColumnType("numeric");

                    b.Property<string>("InvestigatingOfficerName")
                        .HasColumnType("text");

                    b.Property<string>("InvestigatingOfficerRank")
                        .HasColumnType("text");

                    b.Property<decimal?>("MohasavaLiters")
                        .HasColumnType("numeric");

                    b.Property<string>("OfficeAddress")
                        .HasColumnType("text");

                    b.Property<string>("OfficeName")
                        .HasColumnType("text");

                    b.Property<string>("OfficerRank")
                        .HasColumnType("text");

                    b.Property<string>("PersonToWord")
                        .HasColumnType("text");

                    b.Property<string>("PersonWord")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfIncident")
                        .HasColumnType("text");

                    b.Property<string>("PoliceStation")
                        .HasColumnType("text");

                    b.Property<string>("ProperWord")
                        .HasColumnType("text");

                    b.Property<int?>("SampleNumber")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("TimeFrom")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("TimeTo")
                        .HasColumnType("interval");

                    b.Property<decimal?>("TotalSeizedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("CrimeRegisterId");

                    b.HasIndex("Year", "CaseNumber")
                        .IsUnique();

                    b.ToTable("CrimeRegisters");
                });

            modelBuilder.Entity("CrimePortal.Models.Pancha", b =>
                {
                    b.Property<int>("PanchaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PanchaId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CrimeRegisterId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("PanchaId");

                    b.HasIndex("CrimeRegisterId");

                    b.ToTable("Panchas");
                });

            modelBuilder.Entity("CrimePortal.Models.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SampleId"));

                    b.Property<int>("CrimeRegisterId")
                        .HasColumnType("integer");

                    b.Property<string>("SampleType")
                        .HasColumnType("text");

                    b.HasKey("SampleId");

                    b.HasIndex("CrimeRegisterId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("CrimePortal.Models.SeizedItem", b =>
                {
                    b.Property<int>("SeizedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeizedItemId"));

                    b.Property<decimal?>("ApproxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CrimeRegisterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PropertyClass")
                        .HasColumnType("text");

                    b.Property<string>("PropertyType")
                        .HasColumnType("text");

                    b.HasKey("SeizedItemId");

                    b.HasIndex("CrimeRegisterId");

                    b.ToTable("SeizedItems");
                });

            modelBuilder.Entity("CrimePortal.Models.Pancha", b =>
                {
                    b.HasOne("CrimePortal.Models.CrimeRegister", "CrimeRegister")
                        .WithMany("Panchas")
                        .HasForeignKey("CrimeRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrimeRegister");
                });

            modelBuilder.Entity("CrimePortal.Models.Sample", b =>
                {
                    b.HasOne("CrimePortal.Models.CrimeRegister", "CrimeRegister")
                        .WithMany("Samples")
                        .HasForeignKey("CrimeRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrimeRegister");
                });

            modelBuilder.Entity("CrimePortal.Models.SeizedItem", b =>
                {
                    b.HasOne("CrimePortal.Models.CrimeRegister", "CrimeRegister")
                        .WithMany("SeizedItems")
                        .HasForeignKey("CrimeRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrimeRegister");
                });

            modelBuilder.Entity("CrimePortal.Models.CrimeRegister", b =>
                {
                    b.Navigation("Panchas");

                    b.Navigation("Samples");

                    b.Navigation("SeizedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
