services:
  - type: web
    name: crimeportal
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:80
      - key: ConnectionStrings__DefaultConnection
        value: User Id=postgres.kfkuhonsinmmomxeuqfp;Password=Pravin@100000;Server=aws-1-ap-southeast-1.pooler.supabase.com;Port=5432;Database=postgres
      - key: ConnectionStrings__CrimeRegisterConnection
        value: User Id=postgres.kfkuhonsinmmomxeuqfp;Password=Pravin@100000;Server=aws-1-ap-southeast-1.pooler.supabase.com;Port=5432;Database=postgres
    healthCheckPath: /
